CREATE TABLE [dbo].[DealState]
(
	[DealStateId] INT NOT NULL PRIMARY KEY NONCLUSTERED IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	[Order] INT NOT NULL DEFAULT 1,
	[IsCompleted] BIT NOT NULL DEFAULT 0,
)

GO

CREATE CLUSTERED INDEX [IX_DealState_Column] ON [dbo].[DealState] ([Order] ASC)
